apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2-location-service-deployment
  labels:
    app: p2
    service: location-service
    deployment: uat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: p2
      service: location-service
  template:
    metadata:
      labels:
        app: p2
        service: location-service
    spec:    
      containers:
      - name: p2-location-service   
        image: gcr.io/gifted-pulsar-279818/p2-location-service 
        imagePullPolicy: Always
        env:
        - name: P2_Host
          value: "10.42.224.3"
        - name: P2_Database
          value: "LOTR-mirco"
        - name: P2_User
          value: "FellowshipMembers"
        - name: P2_Password
          value: 
        ports:
        - containerPort: 2006
        livenessProbe:
          httpGet:
            path: /health
            port: 2007
          initialDelaySeconds: 3
          periodSeconds: 3
