apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2-location-service-deployment
  namespace: p2-namespace
  labels:
    app: p2
    service: location-service
    deployment: uat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: p2
      service: location-service
  template:
    metadata:
      labels:
        app: p2
        service: location-service
    spec:    
      containers:
      - name: p2-location-service   
        image: gcr.io/gifted-pulsar-279818/p2-location-service 
        imagePullPolicy: Always
        env:
        - name: LB_Host
          value: "10.42.224.3"
        - name: P2_Database
          value: "LOTR-mirco"
        - name: P2_User
          value: "FellowshipMembers"
        - name: LB_BASE_PATH
          value: "/location-service"
        - name: P2_USER_SERVICE_HOST
          value: "http://p2-user-service-service:2007/P2-Fellowship-User-Service"  
        - name: P2_Password
          valueFrom:
            secretKeyRef:
              name: p2-user-service-secrets
              key: password 
        ports:
        - containerPort: 2006
        livenessProbe:
          httpGet:
            path: /health
            port: 2006
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 2006
          initialDelaySeconds: 3
          periodSeconds: 3
