apiVersion: v1
kind: Service
metadata:
  name: p2-location-service-service
  namespace: p2-project
spec:
  type: NodePort
  selector:
    app: p2
    service: location-service
  ports:
    - protocol: TCP
      port: 2006
      targetPort: 2006
