apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: p2-ingress
  namespace: p2-namespace
spec:
  rules:
  - http:
      paths:
      - path: /user-service/*
        backend:
          serviceName: p2-user-service-service
          servicePort: 2007