apiVersion: v1
kind: Service
metadata:
  name: p2-user-service-service
  namespace: p2-project
spec:
  type: NodePort
  selector:
    app: p2
    service: user-service
  ports:
    - protocol: TCP
      port: 2007
      targetPort: 2007
