apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2-user-service-deployment
  labels:
    app: p2
    service: user-service
    deployment: uat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: p2
      service: user-service
  template:
    metadata:
      labels:
        app: p2
        service: user-service
    spec:    
      containers:
      - name: p2-user-service   
        image: gcr.io/gifted-pulsar-279818/p2-user-service 
        imagePullPolicy: Always
        env:
        - name: LB_Host
          value: "10.42.224.3"
        - name: P2_Database
          value: "LOTR-mirco"
        - name: P2_User
          value: "FellowshipMembers"
        - name: LB_BASE_PATH
          value: "/P2-Fellowship-User-Service"
        - name: P2_Password
          valueFrom:
            secretKeyRef:
              name: p2-user-service-secrets
              key: password 
        ports:
        - containerPort: 2007
        livenessProbe:
          httpGet:
            path: /health
            port: 2007
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 2007
          initialDelaySeconds: 3
          periodSeconds: 3
